[package]
name = "rust-exercise"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
  "variables",
  "functions",
  "if",
  "primitive_types",
  "vectors",
  "move_semantics",
  "structs",
  "enums",
  "strings",
  "modules",
  "hashmaps",
]
